#Config file to run the pipeline
#The yaml file contains most of the parameters needed to run the pipeline

simulation:
  path_simulation: /n17data/sguerrini/GowerStreetSims/
  path_info: /n17data/sguerrini/GowerStreetSims/PKDGRAV3_on_DiRAC_DES_330 - Sheet1.csv
  path_output: /n17data/sguerrini/GowerStreetSims/processed/
  sim_number: 1 #The index of the simulation to run (all to run with all simulations)
  sim_name: GowerStreet #Only GowerStreet is currently supported

preprocessing: #Hyperparameter for the preprocessing step
  nside: 512

ray_tracing: #Hyperparameters for the ray-tracing
  method: glass #Currently supports glass and bornraytrace
  save_ray_tracing: F

intrinsic_alignment:
  add_ia: T
  A_ia: 0.49
  eta_ia: 0.

redshift_distribution:
  weight_w_redshift: T
  path_dndz: /n17data/mkilbing/astro/data/CFIS/v1.0/nz/dndz_SP_A.txt
  save: T

shape_noise:
  add_shape_noise: T
  path_gal: /n17data/mkilbing/astro/data/CFIS/v1.0/SP_LFmask/unions_shapepipe_2022_v1.3_mtheli8k.fits
  ra_col: RA
  dec_col: DEC
  e1_col: e1
  e2_col: e2
  w_col: w
  save: T

verbose: T

validation_plot: T