#Config file to run the pipeline
#The yaml file contains most of the parameters needed to run the pipeline

simulation:
  path_simulation: /n17data/sguerrini/GowerStreetSims/
  path_info: /n17data/sguerrini/GowerStreetSims/PKDGRAV3_on_DiRAC_DES_330 - Sheet1.csv
  path_output: /n17data/sguerrini/GowerStreetSims/processed/
  sim_number: 1 #The index of the simulation to run (all to run with all simulations)
  sim_name: GowerStreet #Only GowerStreet is currently supported

preprocessing: #Hyperparameter for the preprocessing step
  nside: 512

ray_tracing: #Hyperparameters for the ray-tracing
  method: glass #Currently supports glass and bornraytrace
  save_ray_tracing: F

intrinsic_alignment:
  add_ia: T
  prior_A_ia: [-3., 3.]
  prior_eta_ia: [-5., 5.]

redshift_distribution:
  weight_w_redshift: T
  nbins: 5
  path_dndz: /home/guerrini/UNIONS_forward_model/data_utils/dndz.txt
  save: F

shape_noise:
  add_shape_noise: T
  path_gal: /n17data/mkilbing/astro/data/CFIS/v1.0/SP_LFmask/unions_shapepipe_2022_v1.3_mtheli8k.fits
  ra_col: RA
  dec_col: DEC
  e1_col: e1
  e2_col: e2
  w_col: w
  save: T

psf_systematic:
  add_systematic: T
  path_psf: /n17data/mkilbing/astro/data/CFIS/v1.0/SP_LFmask/unions_shapepipe_star_2022_v1.3_mtheli8k.fits
  path_prior_params: /home/guerrini/UNIONS_forward_model/data_utils/prior_psf_sys_SP_v1.3_LFmask_8k.npy
  ra_col: RA
  dec_col: DEC
  e1_psf_col: E1_PSF_HSM
  e2_psf_col: E2_PSF_HSM
  size_psf_col: T_PSF_HSM
  e1_star_col: E1_STAR_HSM
  e2_star_col: E2_STAR_HSM
  size_star_col: T_STAR_HSM
  square_size: False
  hdu: 1

verbose: T

validation_plot: T