#Config file to run the pipeline
#The yaml file contains most of the parameters needed to run the pipeline

simulation:
  path_simulation: /lustre/fsmisc/dataset/GowerStreetSims/
  path_info: /lustre/fsmisc/dataset/GowerStreetSims/PKDGRAV3_on_DiRAC_DES_330 - Sheet1.csv
  path_output: /lustre/fswork/projects/rech/prk/uid35yw/test_gss/
  sim_number: 1 #The index of the simulation to run (all to run with all simulations)
  sim_name: GowerStreet #Only GowerStreet is currently supported

preprocessing: #Hyperparameter for the preprocessing step
  nside: 512

ray_tracing: #Hyperparameters for the ray-tracing
  method: glass #Currently supports glass and bornraytrace
  save_ray_tracing: F
  reduced_shear: T

intrinsic_alignment:
  add_ia: T
  prior_A_ia: [-3., 3.]
  prior_eta_ia: [-5., 5.]

redshift_distribution:
  weight_w_redshift: T
  nbins: 1
  path_dndz: /lustre/fswork/projects/rech/prk/uid35yw/UNIONS_forward_model/data_utils/dndz_SP_A.txt
  save: T
  save_cl: T
  #m_bias: /lustre/fswork/projects/rech/prk/uid35yw/UNIONS_forward_model/data_utils/m_bias_prior.txt
  #delta_z: /lustre/fswork/projects/rech/prk/uid35yw/UNIONS_forward_model/data_utils/delta_z_prior.txt
  bias_sc: 1.0

shape_noise:
  add_shape_noise: T
  path_gal: /lustre/fsn1/projects/rech/prk/uid35yw/unions_shapepipe_2022_v1.3_mtheli8k.fits
  ra_col: RA
  dec_col: Dec
  e1_col: e1
  e2_col: e2
  w_col: w
  save: T

psf_systematic:
  add_systematic: T
  path_psf: /lustre/fsn1/projects/rech/prk/uid35yw/unions_shapepipe_star_2022_v1.3_mtheli8k.fits
  path_prior_params: /lustre/fswork/projects/rech/prk/uid35yw/UNIONS_forward_model/data_utils/prior_psf_sys_SP_v1.3_LFmask_8k.npy
  ra_col: RA
  dec_col: DEC
  e1_psf_col: E1_PSF_HSM
  e2_psf_col: E2_PSF_HSM
  size_psf_col: T_PSF_HSM
  e1_star_col: E1_STAR_HSM
  e2_star_col: E2_STAR_HSM
  size_star_col: T_STAR_HSM
  square_size: False
  hdu: 1

n_noise_real: 2
rot_ra: [0, 1, 2, 3, 4] #Rotation in RA of the footprint (list included in [0, 1, 2, 3, 4])
rot_dec: [0, 1, 2, 3, 4] #Rotation in DEC of the footprint (list included in [0, 1, 2, 3, 4])

verbose: T

validation_plot: F
